.\" -*- Nroff -*-
.TH PRCS-DIFF-COMMAND 1 "PRCS Utilities" "Jun/03/1999" "PRCS Utilities"
.SH NAME
prcs-diff-command \- Simple example for $PRCS_DIFF_COMMAND
.SH SYNOPSIS
.B PRCS_DIFF_COMMAND=prcs-diff-command prcs diff 
[\fI...\fR]
.SH "DESCRIPTION"
This manual page documents briefly the
.BR prcs-diff-command ,
script.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B prcs-diff-command
is a really simple demonstration on how to treat the arguments of a diff
command for 
.BR prcs (1), 
determined by the environment variable PRCS_DIFF_COMMAND.
Use it as a template for writing a more interesting command.
.SH "SEE ALSO"
.BR prcs (1),
.PP
Info documentation for PRCS (type "info prcs")
.SH AUTHOR
This manual page was written by Rafael Laboissiere <rafael@icp.inpg.fr>,
for the Debian GNU/Linux system (but may be used by others).
