# azure-pipelines.yml - configuration for Azure Pipelines
# Copyright (C) 2020 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
variables:
  package.version: "1.3.4k2"
trigger:
  - master
  - release/**
  - feature/**
stages:
  - stage: Default
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: |
              sudo apt-get install -q --no-install-recommends \
                  rcs \
                  flex \
                  texinfo
            displayName: Install build dependencies
          - bash: |
              autoreconf --install
            displayName: Bootstrap
          - bash: |
              mkdir -p _build
              cd _build
              ../configure
            displayName: Configure
          - bash: |
              make
            displayName: Build
            workingDirectory: _build
          - bash: |
              make VERSION='$(package.version)' dist || exit $?
              mkdir -p ../dist
              mv -f 'prcs-$(package.version)'.tar.* ../dist
            displayName: Make source archive
            workingDirectory: _build
          - publish: dist
            artifact: dist
  - stage: Test
    jobs:
      - job: Test
        strategy:
          matrix:
            Ubuntu:
              VM_IMAGE: ubuntu-latest
              CC: gcc
              CXX: g++
            macOS:
              VM_IMAGE: macOS-latest
              CC: clang
              CXX: clang++ -std=c++11
        continueOnError: true
        pool:
          vmImage: $(VM_IMAGE)
        steps:
          - checkout: none
          - download: current
            artifact: dist
          - bash: |
              $CXX --version
            displayName: Show versions
          - bash: |
              gzip -dc $(Pipeline.Workspace)/dist/'prcs-$(package.version)'.tar.gz | \
              tar -x
            displayName: Unpack
          - bash: |
              ./configure --prefix='$(Build.BinariesDirectory)'
            displayName: Configure
            workingDirectory: prcs-$(package.version)
          - bash: |
              make
            displayName: Build
            workingDirectory: prcs-$(package.version)
          - bash: |
              make install
            displayName: Install
            workingDirectory: prcs-$(package.version)
  - stage: Publish
    dependsOn: Default
    condition: >-
      and(succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/heads/'))
    jobs:
      - job: Publish
        condition: >-
          startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: none
          - download: current
            artifact: dist
          - task: UniversalPackages@0
            inputs:
              command: publish
              publishDirectory: $(Pipeline.Workspace)/dist
              vstsFeedPublish: $(System.TeamProject)/prcs
              vstsFeedPackagePublish: prcs
              versionOption: patch
              packagePublishDescription: >
                This program is a modified version of PRCS.
