#!/bin/sh

branches=
while [ $# -gt 0 ]
do
    case "$1" in
    -r)
	branches="$branches $2"
	shift
	;;
    -*)
	echo >&2 "unkown option $1"
	exit 1
	;;
    *)
	break
	;;
    esac
    shift
done

(
    if [ -z "$branches" ]
    then
	if [ $# = 0 ]
	then
	    prcs info -l
	else
	    prcs info -l "$@"
	fi
    else
	for b in $branches
	do
	    if [ $# = 0 ]
	    then
		prcs info -l --plain-format -r $b
	    else
		prcs info -l --plain-format -r $b "$@"
	    fi
	done
    fi
) | prcs_tree_info | xvcg -




