.TH PRCS-JAVADOC 8 11/5/1999 prcs-javadoc PRCS PRCS
.SH NAME
prcs-javadoc \- creates javadoc documentation for PRCS projects
.SH SYNOPSIS
.B prcs-javadoc
.I "list-of-projects destination-directory"
.SH DESCRIPTION
.PP
.B prcs-javadoc
is a bourne shell script that goes through a list of PRCS projects and runs javadoc through them. Projects do not have to be purely java projects, as long as they have .java files and use packages. It is especially convenient for nightly builds.
.SH OPTIONS
This program takes no options at this time, see the ENVIRONMENT section.
.SH ENVIRONMENT
.TP
.B PRCS_REPOSITORY
see prcs (1)
.PP
.TP
.B JAVA
Path to the java executable, the default is whatever "java" is found in PATH, or if that fails /usr/local/java/bin/java.
.PP
.TP
.B JAVA_ARGS
Arguments to run java with, default is "-mx64m -ms64m" to give java a starting and max heap size of 64 megs, this stuff eats ALOT of RAM.
.PP
.TP
.B JAVA_COMPILER
JIT compiler to use, defaults to "tya" for 1.1 JDKs and "sunwjit" for 1.2 JDKs if it is not set, otherwise does nothing.
.PP
.TP
.B JAVADOC
Class to run for javadoc, defaults to "sun.tools.javadoc.Main".
.PP
.TP
.B JAVADOC_ARGS
Parameters for javadoc, default is "-private" to generate all methods and variables. See "javadoc".
.PP
.TP
.B JAVADOC_IMAGES
Directory where images used by the results of javadoc maybe found. The default is the first directory that has the file "method-index.gif" in it.
.PP
.SH EXAMPLES
prcs-javadoc
.I foo bar baz /var/www/doc-build
.PP
Builds the documentation for files in projects foo, bar and baz and places it into the directory /var/www/doc-build.
.SH BUGS
Does not seem to correctly generate the index.
Doesn't take command line options.
.SH SEE ALSO
.BR prcs (1),\  javadoc,\ java
.SH AUTHOR
This manual page was written by Rafael Kitover <caelum@debian.org>.
