#!/bin/sh -e
# File: postinst
# Description: Postinst file for the Debian prcs package
# Author: Rafael Laboissiere <rafael@debian.org>
# Created on: 29 Oct 1998 14:07:48 +0100
# Last modified on: Tue Jan 18 09:19:34 CET 2000

set -e

case "$1" in
    configure)     
        install-info --quiet --section Development Development \
	   --description="The Project Revision Control System" \
           /usr/share/info/prcs.info
        ;;

    abort-upgrade | abort-deconfigure | abort-remove)
	;;
    *)
	echo "$0: incorrect arguments: $*" >&2
	exit 1
	;;
esac

#DEBHELPER#
