#!/bin/sh -e
# File: prerm
# Description: Postrm file for the Debian prcs package
# Author: Rafael Laboissière <rafael@icp.inpg.fr>
# Created on: 29 Oct 1998 14:07:48 +0100
# Last modified on: Sun Oct 28 18:17:18 CET 2001

set -e

case "$1" in
    remove | upgrade | failed-upgrade | deconfigure )
        install-info --quiet --remove /usr/share/info/prcs.info
	;;
    *)
	echo "$0: incorrect arguments: $*" >&2
	exit 1
	;;
esac

#DEBHELPER#
