#!/usr/local/bin/perl
#                              -*- Mode: Perl -*-
# $Basename: prcs-emerge $
# $Revision: 1.2 $
# Author          : Ulrich Pfeifer
# Created On      : Fri May  2 08:28:20 1997
# Last Modified By: Ulrich Pfeifer
# Last Modified On: Fri May 16 22:51:01 1997
# Language        : CPerl
# Update Count    : 26
# Status          : Unknown, Use with caution!
#

# Josh's notes:

# The latest version of gnuserv I could find that wasn't part of# the
# Xemacs distribution is available from URL:
# ftp://ftp.wellfleet.com/netman/psmith/emacs/gnuserv-2.1alpha.tar.gz

# To install for FSF emacs, put gnuserv.el in your path and delete
# any server-start command in your .emacs, remove any loading of
# server.el, require gnuserv, run gnuserv-start, and test with
# gnudoit "(message \"hi\")" from the command line.  For example:

# (require 'gnuserv)
# (gnuserv-start)

# Seems to require perl5.  I don't know perl.

use Cwd;
my $pwd = getcwd;
my (
    $Working_label,
    $Working_file,
    $Common_label,
    $Common_file,
    $Selected_label,
    $Selected_file,
    $Output_file,
   ) = @ARGV;

for ($Working_file, $Common_file, $Selected_file, $Output_file) {
  $_ = $pwd . '/' . $_ unless /^\//;
}

exec 'gnudoit',
    qq[(require \'prcs)],
    qq[(prcs::emerge
	"$Working_file"
	"$Common_file"
	"$Selected_file"
	"$Output_file")];
