/* -*-Mode: C;-*-
 * PRCS - The Project Revision Control System
 * Copyright (C) 1996, 1997  Josh MacDonald
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * This file was automatically generated by Emacs and the source
 * file /home/jmacd/nfs/projects/prcs1/doc/prcs.texi at Sun May  9 17:41:14 2004: DO NOT EDIT.
 */

struct EnvName { const char* var; const char* defval; };
extern const EnvName env_names[];
extern const int env_names_count;
extern const char options_summary[];
extern const char checkout_help_string[];
extern const char populate_help_string[];
extern const char depopulate_help_string[];
extern const char checkin_help_string[];
extern const char diff_help_string[];
extern const char merge_help_string[];
extern const char rekey_help_string[];
extern const char info_help_string[];
extern const char changes_help_string[];
extern const char admin_compress_help_string[];
extern const char admin_uncompress_help_string[];
extern const char admin_access_help_string[];
extern const char admin_rebuild_help_string[];
extern const char admin_init_help_string[];
extern const char admin_pdelete_help_string[];
extern const char admin_pinfo_help_string[];
extern const char admin_prename_help_string[];
extern const char config_help_string[];
extern const char package_help_string[];
extern const char unpackage_help_string[];
extern const char execute_help_string[];
extern const char delete_help_string[];
extern const char general_help_string[];
extern const char admin_help_string[];
